/*** Constructor: it is a block(that is similar to method) have same name and as that of class name
 * it does not have any return type, not even void
 * the only modifier for constructor are public , protected , private and default
 * it execute automatically, we create an object
 * use:- to initialized an object ,not create an object
 * type of constructor: 1 . Default (No- argument constructor)- generated by compiler;
 * 2. No-Argument Constructor(user defined)
 * 3. Parameterized constructor
 * 
 * 
 */

class Employee{
    String Name;
    int id;

    Employee(String Name, int id){
        this.Name=Name;
        this.id= id;
    }
}
public class Constructor1 {
    public static void main(String[] args) {
        Employee e1= new Employee("Shyam" , 25);
        Employee e2= new Employee("Abc" , 55);
        Employee e3= new Employee("Xyz" , 15);
        System.out.println(e1.Name + " "+ e1.id);
        System.out.println(e2.Name + " "+ e2.id);
        System.out.println(e3.Name + " "+ e3.id);
        
    }
}
